/* 
 * This file was generated by the PLU Config Tool.
 * 6 Inputs 26 LUTs 4 flip flops and 8 outputs */

/* LUT4 (CLK1_p) */
PLU->LUT[4].INP_MUX[0] = 0x00000001; /* IN1 (CLKOUT_in) */
PLU->LUT[4].INP_MUX[1] = 0x0000003F; /* default */
PLU->LUT[4].INP_MUX[2] = 0x0000003F; /* default */
PLU->LUT[4].INP_MUX[3] = 0x0000003F; /* default */
PLU->LUT[4].INP_MUX[4] = 0x0000003F; /* default */
PLU->LUT_TRUTH[4] = 0xaaaaaaaa; /* CLK1_p CUSTOM */

/* LUT5 (CLK1_n) */
PLU->LUT[5].INP_MUX[0] = 0x00000001; /* IN1 (CLKOUT_in) */
PLU->LUT[5].INP_MUX[1] = 0x0000003F; /* default */
PLU->LUT[5].INP_MUX[2] = 0x0000003F; /* default */
PLU->LUT[5].INP_MUX[3] = 0x0000003F; /* default */
PLU->LUT[5].INP_MUX[4] = 0x0000003F; /* default */
PLU->LUT_TRUTH[5] = 0x55555555; /* CLK1_n CUSTOM */

PLU->OUTPUT_MUX[0] = 0x00000005; /* LUT5 (CLK1_n) -> CLK1_n_PLU_OUT */
PLU->OUTPUT_MUX[4] = 0x00000004; /* LUT4 (CLK1_p) -> CLK1_p_PLU_OUT */
